erDiagram
    forms ||--o{ form_questions : "has"

    rules }o--|| form_questions : "source"
    rules }o--|| form_questions : "target"

    forms ||--o{ form_submissions : "has"
    form_submissions ||--o{ submission_answers : "has"

    submission_answers }o--|| form_questions: "answers"
    
    
    forms {
        uuid id PK
        string name
        string description
        timestamp created_at
        timestamp updated_at
        timestamp deleted_at
    }

    form_questions {
        uuid id PK
        uuid form_id FK
        string type
        string label
        int order
        bool required
        jsonb config
        timestamp created_at
        timestamp updated_at
        timestamp deleted_at
    }

    rules {
        uuid id PK
        uuid source_question_id FK
        string operator
        jsonb trigger_value
        uuid target_question_id FK
        string action_type
        timestamp created_at
        timestamp updated_at
        timestamp deleted_at
    }

    form_submissions {
        uuid id PK
        uuid form_id FK
        timestamp submitted_at
    }

    submission_answers {
        uuid id PK
        uuid submission_id FK
        uuid question_id FK
        string question_type
        jsonb value
    }
